apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "signer.roleName" . }}
  labels:
    {{- include "signer.labels" . | nindent 4 }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - verbs:
      - delete
      - get
      - list
      - watch
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
  - verbs:
      - update
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/status
  - verbs:
      - sign
    apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - unito.it/vault-signer
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events